# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fibonacci(limit, i)
  fibonacci_numbers = []
  sum = 0
  until (i >= limit)
    if (i == 1)
    i2 = 0
    end
    i2 = i2 + i
    fibonacci_numbers << i2
    i = i2 + i
    fibonacci_numbers << i
  end
    for number in  fibonacci_numbers
      if (number % 2 == 0)
        sum += number
      end

    end

  return sum
end


puts fibonacci(4000000, 1)
